### ISSUE TITLE
Adaptor used in vision encoder or text encoder?

### ISSUE THREAD

**Issue by jingzhengli** [gaopengcuhk/Tip-Adapter#9]
Hey, Thanks for nice work. I have some confusion as follows. 
First, why the adaptor is used only in vision encoder, did the authors try to use the adaptor in text encoder? 
Second, I don't understand why using adaptor performs better using learnable prompt. In addition, the "adaptor" used in this paper is different from the adaptor in NLP tasks, also the position of the insertion is different, which one is better?

**Comment by adrielkuek** [comment]
Hi @jingzhengli, base on my understanding in trying to play around with the model architecture, the adapter is built on top of both the vision and text encoders (not just the visual). The main thing is that images are used as the keys rather than texts because the main motivation to few-shot classification is to predict a new associated label for the corresponding image, therefore the labels (text one-hot encoding) has to be fixed otherwise it would not make any sense.
In a way, the idea of mounting adapters is somewhat similar to that in NLP tasks, but the main difference here is that the authors are using a powerful VL model (CLIP) as the backbone to enforce few-shot alignment. Whereas the prompt learning in NLP could come in many forms (soft vs hard prompts), also the position of insertion matters (last layer vs FFN vs self-attention etc.). In TIP-adapter, I guess the main motivation is training free, thus keeping the CLIP backbone frozen is a pretty attractive option. Just my thoughts here. Hope it helps!

**Comment by jingzhengli** [comment]
> Hi @jingzhengli, base on my understanding in trying to play around with the model architecture, the adapter is built on top of both the vision and text encoders (not just the visual). The main thing is that images are used as the keys rather than texts because the main motivation to few-shot classification is to predict a new associated label for the corresponding image, therefore the labels (text one-hot encoding) has to be fixed otherwise it would not make any sense. In a way, the idea of mounting adapters is somewhat similar to that in NLP tasks, but the main difference here is that the authors are using a powerful VL model (CLIP) as the backbone to enforce few-shot alignment. Whereas the prompt learning in NLP could come in many forms (soft vs hard prompts), also the position of insertion matters (last layer vs FFN vs self-attention etc.). In TIP-adapter, I guess the main motivation is training free, thus keeping the CLIP backbone frozen is a pretty attractive option. Just my thoughts here. Hope it helps!

Thanks for your insightful comments, I agree with you. 
Two addtional points of my own: 1) fusing semantic information from text encoder at classification head could boost performance; 2) The adapter acts like few-shot classification when not trained, and acts like "Linear probing" when trained.
